name: foodies
description: "A Recipe app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  alarm: ^3.1.2
  animated_flip_counter: ^0.3.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.1.0
  lottie: ^3.1.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/audio/
    - assets/lottie/
    - assets/images/
  fonts:
    - family: Bauhaus
      fonts:
        - asset: fonts/bauhaus/regular.ttf
        - asset: fonts/bauhaus/bold.ttf
          weight: 700
        - asset: fonts/bauhaus/italic.ttf
          style: italic
        - asset: fonts/bauhaus/bold_italic.ttf
          weight: 700
          style: italic
