name: foodies
description: "A Recipe app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  lottie: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  wheel_picker: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/images/
    - assets/thumbnails/
    - assets/food_images/
